version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workdb

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-container
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "9999:9999"